name: Production Tag Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to every tag not containing /
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.deploy-to-vercel.outputs.console }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: echo "console=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
        id: deploy-to-vercel
      - name: Leave Comment on Commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Successfully deployed to the following URLs:

            ## paperrolls – ./

            [paperrolls-lzmxya.vercel.app](https://paperrolls-lzmxya.vercel.app)
            [paperrolls-git-master-lzmxya.vercel.app](https://paperrolls-git-master-lzmxya.vercel.app)
            [paperrolls.vercel.app](https://paperrolls.vercel.app)

            ## Preview URL of this commit deployment

            ${{ steps.deploy-to-vercel.outputs.console }}